### ISSUE TITLE
I seem to have "BrokenPipeError" when i run test_nas_video_process.py

### ISSUE THREAD

**Issue by JiangShanCode** [kaist-ina/NAS_public#21]
I have the error log:
model_loading [elapsed] : 0.03586411476135254sec
encode [after video info]: 1.9073486328125e-06sec
encode [start]: 0.046860694885253906sec
decode [configuration]: 0.050164222717285156sec
decode [video read prepare]: 0.06549692153930664sec
decode [prepare_frames-96]: 0.3793065547943115sec
Process Process-3:
Traceback (most recent call last):
  File "/home/docker/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/docker/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/docker/workspace/NAS_public/process.py", line 366, in encode
    pipe.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
decode [super-resolution]: 2.427304744720459sec

How to solve the problem,please?

**Comment by chaos5958** [comment]
Have you use the opencv package specific in README? 
I experienced the similar issue when I used the different versions of opencv.
